server:
  port: 8000
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}:${random.int}
spring:
  application:
    name: platform-eureka
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3336/db2019?useSSL=false

management:
  endpoints:
    web:
      exposure:
        include: '*'