server:
  port: 10000
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}/${random.int}
spring:
  profiles:
    active: dev
  application:
    name: platform-gateway
  redis:
    host: localhost
    timeout: 1000
    database: 0
    port: 6379
    lettuce:
      pool:
        max-active: 30
        max-wait: 10000
        max-idle: 30
        min-idle: 10

  cloud:
    gateway:
      # 动态路由
            discovery:
              locator:
                enabled: true
                lower-case-service-id: true
      # 静态路由
#      routes:
#        - id: default_id
#          uri: lb://PLATFORM-CONSUMER
#          #          uri: http://localhost:9001
#          predicates:
#            #            - Method=GET
#            #            - RemoteAddr=192.168.3.88/0
#            #            - Query=name
#            #            - Query=name, 1.
#            - Path=/hello1/**
#          #          # 注意有个 s
#          filters:
#            - name: RequestRateLimiter
#              args:
#                key-resolver: '#{@apiKeyResolver}'
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 3
#            - Custom=aa,bb


logging:
  level:
    org.springframework.cloud.gateway: debug
---
spring:
  profiles: prod
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka:8000/eureka

---
spring:
  profiles: dev
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8000/eureka


